import argparse
import csv
import secrets
import string
import subprocess
from typing import List, Tuple


# Alphabet “sûr” (pas d'espaces)
LOWER = string.ascii_lowercase
UPPER = string.ascii_uppercase
DIGITS = string.digits
SPECIAL = "!@#$%^&*()-_=+[]{};:,.?/"
ALL = LOWER + UPPER + DIGITS + SPECIAL


def generate_password(length: int) -> str:
    """
    Génère un mot de passe long et aléatoire.
    Forçe présence: minuscule, majuscule, chiffre, spécial, puis complète jusqu'à length.
    """
    if length < 16:
        raise ValueError("length doit être >= 16 (recommandé: 24).")

    chars = [
        secrets.choice(LOWER),
        secrets.choice(UPPER),
        secrets.choice(DIGITS),
        secrets.choice(SPECIAL),
    ]

    if length > 4:
        chars += [secrets.choice(ALL) for _ in range(length - 4)]

    secrets.SystemRandom().shuffle(chars)
    return "".join(chars)


def php_password_hash(password: str, php_bin: str) -> str:
    """
    Délègue à PHP pour garantir la compatibilité exacte avec password_hash(PASSWORD_DEFAULT).
    """
    # password_hash($argv[1], PASSWORD_DEFAULT) -> hash bcrypt/argon selon ta version PHP
    res = subprocess.run(
        [php_bin, "-r", "echo password_hash($argv[1], PASSWORD_DEFAULT);", password],
        capture_output=True,
        text=True,
    )
    if res.returncode != 0:
        raise RuntimeError(f"PHP password_hash a échoué: {res.stderr.strip()}")
    return res.stdout.strip()


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def main() -> None:
    ap = argparse.ArgumentParser(description="Génère des comptes admin (mots de passe ou hashes PHP).")
    ap.add_argument("--count", type=int, default=5, help="Nombre d'admins à générer.")
    ap.add_argument("--length", type=int, default=24, help="Longueur mot de passe (>=16). Recommandé: 24.")
    ap.add_argument("--prefix", type=str, default="admin", help="Préfixe username (admin1, admin2, ...).")
    ap.add_argument(
        "--mode",
        type=str,
        default="hash",
        choices=["plaintext", "hash", "both"],
        help="hash = pas de mots de passe en clair (recommandé).",
    )
    ap.add_argument("--php-bin", type=str, default="php", help="Chemin/nom du binaire PHP (ex: php, C:\\wamp64\\...\\php.exe).")
    ap.add_argument("--outfile", type=str, default="", help="Chemin fichier de sortie (CSV ou SQL). Optionnel.")
    args = ap.parse_args()

    rows_plain: List[Tuple[str, str]] = []
    rows_hash: List[Tuple[str, str]] = []

    for i in range(1, args.count + 1):
        username = f"{args.prefix}{i}" if args.count > 1 else args.prefix
        password = generate_password(args.length)

        if args.mode in ("plaintext", "both"):
            rows_plain.append((username, password))

        if args.mode in ("hash", "both"):
            h = php_password_hash(password, args.php_bin)
            rows_hash.append((username, h))

    if args.mode == "plaintext":
        if args.outfile:
            with open(args.outfile, "w", newline="", encoding="utf-8") as f:
                w = csv.writer(f)
                w.writerow(["username", "password"])
                w.writerows(rows_plain)
            print(f"CSV généré: {args.outfile}")
        else:
            for u, p in rows_plain:
                print(f"{u}: {p}")

    elif args.mode == "hash":
        if args.outfile:
            if args.outfile.lower().endswith(".sql"):
                with open(args.outfile, "w", encoding="utf-8") as f:
                    f.write("-- Admin users generated by generate_admin_accounts.py\n")
                    for u, h in rows_hash:
                        f.write(
                            "INSERT INTO admin_users (username, password_hash, is_active) "
                            f"VALUES ('{sql_escape(u)}', '{h}', 1);\n"
                        )
                print(f"SQL généré: {args.outfile}")
            else:
                with open(args.outfile, "w", newline="", encoding="utf-8") as f:
                    w = csv.writer(f)
                    w.writerow(["username", "password_hash"])
                    w.writerows(rows_hash)
                print(f"CSV généré: {args.outfile}")
        else:
            for u, h in rows_hash:
                print(f"{u} -> {h}")

    else:  # both
        if not args.outfile:
            raise SystemExit("Pour mode=both, merci de préciser --outfile (.csv conseillé).")
        if not args.outfile.lower().endswith(".csv"):
            raise SystemExit("Pour mode=both, --outfile doit être un .csv.")

        plain_map = {u: p for u, p in rows_plain}
        with open(args.outfile, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f)
            w.writerow(["username", "password", "password_hash"])
            for u, h in rows_hash:
                w.writerow([u, plain_map.get(u, ""), h])
        print(f"CSV généré: {args.outfile}")


if __name__ == "__main__":
    main()

